substitutions:
  device_name: esphomec5-garage
  friendly_name: Garage C5
  api_key: "ZmFrZWFwaWtleWZha2VleGFtcGxlZmFrZWtleQ=="
  ota_password: "ChangeMe!2025"

packages:
  device: !include "common/Seeed xiao ESP32-c5 base.yaml"
